name: money_book_2022
description: インターンシップ用 お小遣い帳 Flutter アプリ 2022年版

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0+4

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dropdown_button2: ^1.6.2
  google_fonts: ^3.0.1
  intl: ^0.17.0
  package_info_plus: ^1.4.2
  path: ^1.8.1
  path_provider: ^2.0.11
  sqflite: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true

  assets:
    - images/icon.png

flutter_icons: # $ flutter pub pub run flutter_launcher_icons:main
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "images/icon.png"
